# How often the database should be updated in seconds.
refresh: 3600

# If local heads should be enabled. Only starts keeping track of joined players when enabled!
localHeads: true

# If enabled categories will require a permission to be used
# Permission: headdb.category.<category>
requireCategoryPermission: false

# Economy options
economy:
  enable: false
  # Supported: VAULT
  provider: "VAULT"
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
    local: 1000

# UI customization options.
ui:
  category:
    # Head categories. You can use item: instead of head: here, but AIR is not supported.
    alphabet:
      location: 20
      head: 1788
    animals:
      location: 21
      head: 5741
    blocks:
      location: 22
      head: 8624
    decoration:
      location: 23
      head: 11046
    food-drinks:
      location: 24
      head: 17442
    humans:
      location: 29
      head: 19361
    humanoid:
      location: 30
      head: 28320
    miscellaneous:
      location: 31
      head: 32746
    monsters:
      location: 32
      head: 34819
    plants:
      location: 33
      head: 37278
    # Meta categories, used for UI elements. AIR is not supported. You can use head: instead of item: here.
    favorites:
      location: 39
      item: BOOK
    search:
      location: 40
      item: DARK_OAK_SIGN
    local:
      location: 41
      item: COMPASS
    # Item used to fill unused slots in the categories menu. AIR is supported. You can use head: instead of item: here.
    fill:
      item: BLACK_STAINED_GLASS_PANE
  sound:
    # Whether the sounds should be played
    enabled: true

    # Played when a head is taken with no economy plugin
    noEconomy:
      # The name of the sound.
      # Must be one from: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1
      pitch: 1
    # Played when the player doesn't have permission for the menu
    noPermission:
      name: BLOCK_ANVIL_BREAK
      volume: 1
      pitch: 1
    # Played when they purchase a head
    paid:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1
      pitch: 1
    # Played when the head is free
    free:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1
      pitch: 1
    # Played when the player does not have enough funds for the head
    unavailable:
      name: BLOCK_ANVIL_BREAK
      volume: 1
      pitch: 1
    # Played when a category/menu is opened
    open:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1
      pitch: 1
    # Played when a head is added to the favorites list
    addFavorite:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 1
      pitch: 1
      # Played when a head is removed to from favorites list
    removeFavorite:
      name: BLOCK_ANVIL_BREAK
      volume: 1
      pitch: 1

# Debug Mode
debug: false