name: ${project.name}
description: ${project.description}

main: tsp.headdb.HeadDB
version: ${project.version}
softdepend: [Vault, Treasury]
api-version: 1.13
author: Silent

commands:
  headdb:
    usage: /headdb <arguments>
    description: Open the database
    aliases: [hdb, headdatabase, headmenu]

permissions:
  headdb.admin:
    default: op
    children:
      headdb.open: true
      headdb.search: true
      headdb.give: true
      headdb.favorites: true
      headdb.local: true
      headdb.tagsearch: true
      headdb.update: true
      headdb.reload: true
  headdb.open:
    default: op
  headdb.search:
    default: op
  headdb.give:
    default: op
  headdb.favorites:
    default: op
  headdb.local:
    default: op
  headdb.tagsearch:
    default: op
  headdb.update:
    default: op
  headdb.reload:
    default: op